algoritmo "semnome"
// Função :
// Autor :
// Data : 25/04/2022
// Seção de Declarações 
var
qtdemin,qtdemax,estoquemedio:real
inicio
// Dados de entrada
escreval("digite o valor da quantidade minima: ")
leia(qtdemin)
escreval("digite o valor da quantidade maxima: ")
leia(qtdemax)
//processamento
estoquemedio<-(qtdemin+qtdemax)/2
//dados de saída
escreval("O seu estoque medio é: ",estoquemedio)





 
fimalgoritmo
