algoritmo "ex1"

var
v_inicial,v_final,contado,:inteiro
inicio
escreval("Digite o valor inicial de contagem:")
leia(v_inicial)
escreval("Digite o valor final de contagem:")
leia(v_final)
limpatela
escreval("Contagem peresonalizada")
escreval("*********************************")
para contador de v_inicial ate v_final faca
   escreval (contador)
fimpara
escreval("*********************************")
fimalgoritmo
