algoritmo "semnome"
// Função :
// Autor :
// Data : 09/05/2022
// Seção de Declarações 
var
n1,n2,n3,n4,total: real

inicio
// Dados de Entrada

escreval("digite um valor para n1 ")
leia(n1)
escreval("digite um valor para n2 ")
leia(n2)
escreval("digite um valor para n3 ")
leia(n3)
escreval("digite um valor para n4 ")
leia(n4)
// procesamento

total<-(n1*n1)+(n2*n2)+(n3*n3)+(n4*n4)
// dados  de saída

escreval("o seu valor total é: ",total)




fimalgoritmo
