algoritmo "semnome"
var
numero_inicial,numero_final,contador:inteiro
inicio
escreval("Digite o valor inicial da contagem: ")
leia(numero_inicial)
escreval("Digite o valor final da contagem: ")
leia(numero_final)
limpatela
escreval("Contagem personalizada")
escreval("********************************")
para contador de numero_inicial at numero_final faca
   escreval(contador)
   fimpara
   escreval("************************************")
fimalgoritmo
