algoritmo "semnome"
var
nota1,nota2,soma,media:real
contador:inteiro
inicio
para contador de 1 ate 10 faca
escreval("*****************************")
escreval("ALUNO N°  ", contador)
escreval("Digite a nota 1: ")
leia(nota1)
escreval("Digite a nota 2")
leia(nota2)
soma <-nota1+nota2
media <- soma/2
escreval("A media do aluno ",contador," é: ",media)
escreval("*****************************")

fimpara
fimalgoritmo
